[package]
name = "mapi"
version = "0.1.0"
edition = "2021"
authors = ["Panagiotis Koutsourakis <kutsurak@monetdbsolutions.com>"]

[dependencies]
bytes = "0.4.4"
# bytes = "1.1.0"
digest = "0.10.3"
sha2 = "0.10"
ripemd = "0.1.1"
# url = "2.2.2"
url = "1.5.1"
log = "0.4.17"
env_logger = "0.4.3"
