[package]
name = "monetdb"
version = "0.1.0"
authors = ["Panagiotis Koutsourakis <kutsurak@monetdbsolutions.com>"]

[dependencies]
bytes = "0.4.4"
# bytes = "1.1.0"
# url = "2.2.2"
url = "1.5.1"
log = "0.4.17"
env_logger = "0.4.3"

mapi = {version = "0.1.0", path = "../mapi"}