name: Rust

on: [push]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  linter:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy

  linux:
    runs-on: ubuntu-latest
    needs: linter
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  macos:
    runs-on: macOS-latest
    needs: linter
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  # windows:
  #   runs-on: windows-latest
  #   needs: linter
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build
  #     run: cargo build --verbose
  #   - name: Run tests
  #     run: cargo test --verbose