name: Rust

on: [push]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  linter:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy

  build:
    strategy:
      matrix:
        os: [ubuntu, macOS]
    runs-on: ${{ matrix.os }}-latest
    needs: linter
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  # integration-tests:
  #   strategy:
  #     matrix:
  #       os: [ubuntu]
  #   runs-on: ${{ matrix.os }}-latest
  #   needs: build
  #   services:
  #     monetdb:
  #       image: monetdb/vessel_ai
  #       env: 
  #         DB_HOST: localhost
  #         DB_PORT: 50000
  #         DB_NAME: demo
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Integration Tests
  #     run: cargo t --features integration
